name: Pulumi ðŸ”„

on:
  push:
    branches:
      - prod
      - preprod
  workflow_dispatch:

env:
  # IMPORTANT! You must map the env vars for your providers here even though you add them as secrets in GitHub
  # See the setup page for providers here: https://www.pulumi.com/docs/intro/cloud-providers/
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_STACK_NAME: ginetta/ginetta-tonic-festival
  PULUMI_WORKING_DIRECTORY: ./infrastructure/
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  pulumi:
    runs-on: ubuntu-latest
    name: Pulumi
    steps:
      - name: Checkout ${{ github.ref_name }} ðŸ“¥
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install Dependencies ðŸ“¦
        run: yarn install --immutable
        working-directory: ${{ env.PULUMI_WORKING_DIRECTORY }}

      - name: PR previews
        if: ${{ github.event_name == 'pull_request' }}
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}

      - name: Apply infrastructure update ðŸš€
        if: ${{ github.event_name == 'push' }}
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}

      # If you'd like to run your Pulumi application outside of the official GitHub Action

      #- name: Install Pulumi CLI
      #  uses: pulumi/setup-pulumi@v2

      #- name: PR previews
      #  run: pulumi preview -s $PULUMI_STACK_NAME --cwd $PULUMI_WORKING_DIRECTORY
      #  if: ${{ github.event_name == 'pull_request' }}

      #- name: Apply infrastructure update
      #  run: pulumi update --yes -s $PULUMI_STACK_NAME --cwd $PULUMI_WORKING_DIRECTORY
      #  if: ${{ github.event_name == 'push' }}
